# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identifier')),
                ('active', models.BooleanField(default=True, help_text='Should this entry be visible for users?', verbose_name='active')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year')),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, verbose_name='month')),
                ('day', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], null=True, verbose_name='day')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Type !MORE to hide some text in a spoiler. A "Show more" button will be displayed.', verbose_name='description')),
                ('sort', models.SmallIntegerField(blank=True, help_text='When some entries match the same number of tags when user performs a search, the results will be sorted ascending by this parameter.', null=True, verbose_name='force ordering')),
                ('file', models.FileField(blank=True, help_text='Np. zdjęcie, film, plik MP3...', null=True, upload_to='', verbose_name='file')),
                ('mime_type', models.CharField(blank=True, editable=False, help_text='This field will be automagically populated after uploading a file.', max_length=255, null=True, verbose_name='mime type')),
                ('md5sum', models.CharField(blank=True, editable=False, help_text='This field will be automagically populated after uploading a file.', max_length=36, null=True, unique=True, verbose_name='MD5 checksum')),
            ],
            options={
                'verbose_name_plural': 'entries',
                'verbose_name': 'entry',
                'ordering': ('year', 'month', 'day', 'title', 'description'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'tags',
                'verbose_name': 'tag',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Add new tags by pressing the plus button or choose existing ones by moving them from "Available" to "Chosen" (select and press the right arrow).', to='smmc.Tag', verbose_name='tags'),
        ),
    ]
